### ISSUE TITLE
Add support for Java 9!

### ISSUE THREAD

**Issue by aadrian** [JFormDesigner/markdown-writer-fx#25]
Please add support for Java 9 too.

The Travis-CI relevant part of the build matrix for Java 9:
```yml
    - dist: trusty
      group: edge
      jdk: oraclejdk9
      sudo: required
      addons:
        apt:
          packages:
            - oracle-java9-installer
```

Thank you.
